# Generated by Django 3.2.9 on 2021-12-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=6)),
                ('group_course', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TGPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('question_group', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('open_period', models.IntegerField()),
                ('options', models.TextField()),
                ('correct_option', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('list_number', models.IntegerField()),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webBot.group')),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField()),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webBot.student')),
            ],
        ),
    ]
