# Generated by Django 4.0 on 2021-12-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=6)),
                ('group_course', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField()),
                ('registration_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('question', models.CharField(max_length=255)),
                ('question_number', models.IntegerField()),
                ('user_answer', models.CharField(blank=True, default='empty', max_length=255)),
                ('user_image', models.TextField(blank=True, default='empty')),
                ('is_closed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBot.chatuser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('list_number', models.IntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBot.group')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('poll_id', models.IntegerField()),
                ('question_group', models.IntegerField()),
                ('question_number', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('options', models.TextField()),
                ('correct_option', models.IntegerField()),
                ('open_period', models.IntegerField(blank=True, default=604800)),
                ('user_choice', models.IntegerField(blank=True, default=-1)),
                ('is_closed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBot.chatuser')),
            ],
        ),
        migrations.AddField(
            model_name='chatuser',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webBot.student'),
        ),
    ]
