# Generated by Django 3.2.9 on 2021-12-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0002_alter_student_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('poll_id', models.IntegerField()),
                ('question_group', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('options', models.TextField()),
                ('correct_option', models.IntegerField()),
                ('open_period', models.IntegerField(blank=True)),
                ('user_choice', models.IntegerField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBot.chatuser')),
            ],
        ),
        migrations.DeleteModel(
            name='TGPoll',
        ),
    ]
