# Generated by Django 3.2.9 on 2021-12-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0003_auto_20211204_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepoll',
            name='open_period',
            field=models.IntegerField(blank=True, default=604800),
        ),
        migrations.AlterField(
            model_name='simplepoll',
            name='user_choice',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
