# Generated by Django 3.2.9 on 2021-12-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0004_auto_20211204_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepoll',
            name='message_id',
            field=models.BigIntegerField(),
        ),
    ]
