# Generated by Django 3.2.9 on 2021-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0005_alter_simplepoll_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepoll',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
