# Generated by Django 3.2.9 on 2021-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0006_simplepoll_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepoll',
            name='is_closed',
            field=models.BooleanField(),
        ),
    ]
