# Generated by Django 3.2.9 on 2021-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0008_alter_simplepoll_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepoll',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
    ]
