# Generated by Django 3.2.9 on 2021-12-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0010_alter_simplepoll_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('question', models.CharField(max_length=255)),
                ('question_number', models.IntegerField()),
                ('user_answer', models.CharField(blank=True, max_length=255)),
                ('user_image', models.IntegerField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBot.chatuser')),
            ],
        ),
    ]
