# Generated by Django 3.2.9 on 2021-12-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0014_alter_textquestion_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='user_image',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
