# Generated by Django 3.2.9 on 2021-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0015_alter_textquestion_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='user_image',
            field=models.TextField(blank=True, default='empty'),
        ),
    ]
