# Generated by Django 4.0 on 2021-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0016_alter_textquestion_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='is_group_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
