# Generated by Django 4.0 on 2021-12-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0018_remove_chatuser_is_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBot.student'),
        ),
    ]
