# Generated by Django 4.0 on 2021-12-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webBot', '0019_alter_chatuser_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField()),
                ('registration_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='registration_state',
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webBot.student'),
        ),
    ]
